name: "godot-ci export"
on: [push, pull_request]
permissions:
  contents: read
  pages: write
  id-token: write
env:
  GODOT_VERSION: 3.5.1

jobs:
  export:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.5.1
    strategy:
      fail-fast: false
      matrix:
        platform: [ windows, mac, linux, web ]
        type: [ export, export-debug ]
        include:
          - platform: windows
            export: robot-gem.exe
          - platform: linux
            export: robot-gem
          - platform: web
            export: index.html
        exclude:
          - platform: mac
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -vp ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Build
        run: |
          mkdir -vp build/${{ matrix.platform }}
          godot -v --${{ matrix.type }} ${{ matrix.platform }} build/${{ matrix.platform }}/${{ matrix.export }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.platform }}
          path: build/${{ matrix.platform }}
      - name: Create zip
        run: zip ${{ matrix.platform }}.zip build/${{ matrix.platform}}/*
      - name: Upload Zipped Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.platform }}-zipped
          path: ${{ matrix.platform }}.zip
  ghp-upload:
    runs-on: ubuntu-latest
    needs:
      - export
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - run: mkdir _site
      - run: mkdir _site/{download,play}
      - name: Download for playing
        uses: actions/download-artifact@v1
        with:
          name: web
          path: _site/play
      - name: Download windows for downloading
        uses: actions/download-artifact@v1
        with:
          name: windows-zipped
          path: _site/download/windows.zip
      - name: Download linux for downloading
        uses: actions/download-artifact@v1
        with:
          name: linux-zipped
          path: _site/download/linux.zip
      - name: Download web for hosting
        uses: actions/download-artifact@v1
        with:
          name: web-zipped
          path: _site/download/web.zip
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: _site
  ghp-deploy:
    runs-on: ubuntu-latest
    needs: ghp-upload
    steps:
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v1.2.3