name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 3.3.4
  PROJECT_PATH: ''

jobs:
  export:
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:3.3.4
    strategy:
      matrix:
        platform: [windows, mac, linux, web]
        include:
          - platform: windows
            export: robot-gem.exe
          - platform: linux
            export: robot-gem
          - platform: web
            export: robot-gem.html
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Build
        run: |
          mkdir -v -p build/${{ matrix.platform }}
          cd $PROJECT_PATH
          godot -v --export "Windows Desktop" ../build/${{ matrix.platform }}/${{ matrix.export }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.platform }}
          path: build/${{ matrix.platform }}
